var CommentConstants = {
  POST_ADD: 'POST_ADD',
  POST_FETCHPAGE: 'POST_FETCHPAGE',
  POST_FETCHUSERPAGE: 'POST_FETCHUSERPAGE',
  POST_VOTE: 'POST_VOTE',
  POST_UPDATE: 'POST_UPDATE',
  POST_DELETE: 'POST_DELETE'
};

module.exports = CommentConstants;